name = "my-cloudflare-website"
main = "src/index.ts"
compatibility_date = "2025-02-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

# Routes configuration - uncomment and configure when deploying to a custom domain
# [[routes]]
# pattern = "example.com/*"
# zone_name = "example.com"