name = "my-cloudflare-website"
main = "src/index.ts"
compatibility_date = "2025-02-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "*"
zone_name = "your-domain.com"
custom_domain = true